name: Docs

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - uses: pnpm/action-setup@v4
              with:
                  version: 10

            - run: |
                  cd docs
                  pnpm install
                  pnpm build-storybook
                  git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                  pnpm run deploy --user "github-actions-bot <support+actions@github.com>"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

