name: Docs

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup

            - run: pnpm build
            - run: pnpm --filter docs build-storybook

            - run: |
                  git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                  pnpm --filter docs exec gh-pages -d storybook-static --user "github-actions-bot <support+actions@github.com>"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
