name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  yarn:
    uses: ./.github/workflows/yarn-cache.yml

  lint:
    needs: yarn
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - run: yarn lint

  build:
    needs: yarn
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - run: yarn build

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          cd docs
          yarn install
          yarn build-storybook
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
