name: CI/CD

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    pnpm:
        uses: ./.github/workflows/pnpm-cache.yml

    lint:
        needs: pnpm
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup

            - run: pnpm lint

    typecheck:
        needs: pnpm
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup

            - run: pnpm typecheck

    build:
        needs: pnpm
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup

            - run: pnpm build
